### ISSUE TITLE
自增主键ID更新不了

### ISSUE THREAD

**Issue by vittel215** [bestaone/midway-boot#1]
大哥，我设置自增主键id，更新时候不通过啊

**Comment by bestaone** [comment]
> 大哥，我设置自增主键id，更新时候不通过啊

自增主键的装饰类是这个（但是我们一般不会用自增主键）
```
@PrimaryGeneratedColumn()
id: number;
```
可以参考这里：http://www.midwayjs.org/docs/extensions/orm#5%E5%88%9B%E5%BB%BA%E8%87%AA%E5%A2%9E%E4%B8%BB%E9%94%AE%E5%88%97
