### ISSUE TITLE
能不能增加一个权限验证功能

### ISSUE THREAD

**Issue by anmeng777** [bestaone/midway-boot#3]
首先感谢您设计实现了如此棒的模板项目，让我在nodejs项目中看到了spring boot的影子，还附带一个非常好的入门说明。
想必您是一个技术非常厉害的工程师。
现在我有一个不情之请，我需要一个权限验证功能，但是跟着官网passport-jwt教程做却没有真正实现，这个框架的网络教程也比较少，我是一个Java工程师但是现在需要写一个nodejs框架项目方便部署运维。
如果您能更新一个这个功能就好了，谢谢

**Comment by bestaone** [comment]
要做权限的话，可以加一个权限过滤器，在过滤器中对接口进行权限校验，可以采用RBAC模型。
最近工作太忙，等有空了再来把此部分加上去吧！

**Comment by anmeng777** [comment]
> 要做权限的话，可以加一个权限过滤器，在过滤器中对接口进行权限校验，可以采用RBAC模型。 最近工作太忙，等有空了再来把此部分加上去吧！

谢谢，我最近很忙，如果过阵子忙完会帮您完善
